### ISSUE TITLE
proposal for Bus 15

### ISSUE THREAD

**Issue by xhub** [mosaikberlinsound/m32-scenes-and-presets#5]
proposal for Bus 15: let the sends of voice channels be at 0db. There is a DCA effect that operates on the bus. With current value, the DCA fader has to be high in the plus range to hear the effect kicking in. It is then challenging to fine tune the effect.

**Comment by cabcookie** [comment]
Fixed with https://github.com/mosaikberlinsound/m32-scenes-and-presets/commit/c987212feccd74939fa603273de4cd4451ac852c
