### ISSUE TITLE
Distorted Bass IEM

### ISSUE THREAD

**Issue by ghukar** [mosaikberlinsound/m32-scenes-and-presets#9]
Bass IEM is regularly distorted - it worked today to reduce the Bass IEM Bus volume (Bus 3/4).
I tried -12dB, but less reduction might work, too (-> Bass IEM output of stage box / M32 is overdriving the Fisher Amp).

**Comment by cabcookie** [comment]
Thanks for raising this issue. Did you try another body pack/In Ear amp? The issue could be on the receiving end as well. What do you think?

**Comment by ghukar** [comment]
Since I`m not the only one having this issue (at least two more bass players) I think it is very unlikely that the same body pack got picked every time..

My suggestion is: lowering the volume of Bus 3/4 to about -6dB, the body packs have enough reserve to make up for the volume (had mine turned up about half way at -9dB output from the mixing desk)

**Comment by cabcookie** [comment]
Fixed with https://github.com/mosaikberlinsound/m32-scenes-and-presets/commit/5b723e1f20b4f5f08353f0ad9da2a94ae7c86cb2
